In [0]:
!pip uninstall -y kaggle 
!pip install kaggle==1.5.6
%env KAGGLE_USERNAME =#########
%env KAGGLE_KEY =##############
!kaggle competitions download -c digit-recognizer
!unzip /content/digit-recognizer.zip

Uninstalling kaggle-1.5.6:
  Successfully uninstalled kaggle-1.5.6
Processing /root/.cache/pip/wheels/57/4e/e8/bb28d035162fb8f17f8ca5d42c3230e284c6aa565b42b72674/kaggle-1.5.6-cp36-none-any.whl
env: KAGGLE_USERNAME=mohammedessam97
env: KAGGLE_KEY=fa984ffe1d2b5e20b0cc318f8bde2822
digit-recognizer.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  /content/digit-recognizer.zip
replace sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [0]:
import pandas as pd 
import numpy as np 
import cv2 
X = pd.read_csv("/content/train.csv")


In [0]:
Y = X.iloc[:,0]
X = X.iloc[:,1:785]

In [0]:
X.head()

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0       0       0       0  ...         0         0         0         0
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...         0         0         0         0
3       0       0       0       0  ...         0         0         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]

In [0]:
X /=255.0
X = X.values.reshape(-1,28,28,1)

In [0]:
X = np.array(X)
Y = np.array(Y)

In [0]:
 from sklearn.model_selection import train_test_split
np.random.seed(42)
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.1,random_state=42)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam , RMSprop
from keras.callbacks import ModelCheckpoint
from keras.utils import to_categorical
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D,MaxPool2D
from keras import backend as K
model = Sequential()

model.add(Conv2D(filters = 32, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu', input_shape = (28,28,1)))
model.add(Conv2D(filters = 32, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))


model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.25))


model.add(Flatten())
model.add(Dense(256, activation = "relu"))
model.add(Dropout(0.5))
model.add(Dense(10, activation = "softmax"))
optimizer = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)
model.compile(optimizer = optimizer , loss = "categorical_crossentropy", metrics=["accuracy"])

In [0]:
from keras.callbacks import  ReduceLROnPlateau
learning_rate_reduction = ReduceLROnPlateau(monitor='val_acc', 
                                            patience=3, 
                                            verbose=1, 
                                            factor=0.5, 
                                            min_lr=0.00001)


In [0]:
y_train = to_categorical(y_train,10)
y_test = to_categorical(y_test,10)

In [0]:
print(y_train)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [0]:
model.fit(X_train,y_train,epochs=30,validation_data=(X_test,y_test),batch_size=86)

Train on 37800 samples, validate on 4200 samples
Epoch 1/30
37800/37800 [==============================] - 5s 135us/step - loss: 0.2429 - acc: 0.9233 - val_loss: 0.0756 - val_acc: 0.9757
Epoch 2/30
37800/37800 [==============================] - 5s 120us/step - loss: 0.0724 - acc: 0.9787 - val_loss: 0.0485 - val_acc: 0.9848
Epoch 3/30
37800/37800 [==============================] - 4s 119us/step - loss: 0.0548 - acc: 0.9841 - val_loss: 0.0320 - val_acc: 0.9900
Epoch 4/30
37800/37800 [==============================] - 5s 121us/step - loss: 0.0461 - acc: 0.9865 - val_loss: 0.0308 - val_acc: 0.9907
Epoch 5/30
37800/37800 [==============================] - 5s 122us/step - loss: 0.0392 - acc: 0.9878 - val_loss: 0.0364 - val_acc: 0.9900
Epoch 6/30
37800/37800 [==============================] - 5s 120us/step - loss: 0.0354 - acc: 0.9893 - val_loss: 0.0353 - val_acc: 0.9905
Epoch 7/30
37800/37800 [==============================] - 5s 120us/step - loss: 0.0318 - acc: 0.9907 - val_loss: 0.0285 - v

In [0]:
X=[] 
y=[]
for item in X_train: 
   X.append(item)
for item in X_test: 
   X.append(item)
for item in y_train: 
   y.append(item)
for item in y_test: 
   y.append(item)

In [0]:
X = np.array(X)
y = np.array(y)

In [0]:
model.fit(X,y,epochs=5)

In [0]:
prds = [] 
lbl = [] 
i = 1 
test = pd.read_csv("/content/test.csv")
test = np.array(test)
for item in test : 
    t = np.reshape(item,(1,28,28,1))
    tmp = model.predict(t)
    tmp = np.argmax(tmp)
    prds.append(tmp)
    lbl.append(i)
    i+=1
prds = np.array(prds)
lbl = np.array(lbl)

In [0]:
df = pd.DataFrame(list(zip(lbl, prds)), 
               columns =['ImageId', 'Label']) 

In [0]:
df.to_csv('submission.csv',index=False)

In [0]:
!kaggle competitions submit digit-recognizer -f "submission.csv" -m "MNIST Submission from API"